version: '3.7'
services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ov_movies
    ports:
      - '5432:5432'
  web:
    image: ov-movies/web
    build: .
    env_file: ".env"
    ports:
      - '3000:3000'
