CREATE TABLE screenings (
    id VARCHAR(255) PRIMARY KEY NOT NULL,
    movie_id VARCHAR(255) REFERENCES movies(id) ON DELETE CASCADE,
    date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    cinema VARCHAR(255) NOT NULL,
    "original?" BOOLEAN NOT NULL
);